export enum EstadoPedido {
  PAGO_PENDIENTE = 'PAGO_PENDIENTE',
  PAGO_ENVIADO = 'PAGO_ENVIADO',
  PAGO_VERIFICADO = 'PAGO_VERIFICADO',
  EMPAQUETADO = 'EMPAQUETADO',
  ENVIADO = 'ENVIADO',
  ENTREGADO = 'ENTREGADO',
  CANCELADO = 'CANCELADO',
  PAGO_RECHAZADO = 'PAGO_RECHAZADO'
}
